### ISSUE TITLE
"Attempt to access a missing method" while initiating template studio for WPF

### ISSUE THREAD

**Issue by rrvenki** [microsoft/TemplateStudio#4597] opened 2022-09-06 09:40 UTC
Visual Studio installed - 17.4.0 Preview 1.0
Tried to use "Template Studio for WPF" and "Matt's Template Studio for WPF". Both independently and together (All combinations). Post giving new project name, It takes few seconds and always throws error "Attempt to access a missing method."

Breaking error. unable to proceed to use the template.
For existing template studio created project, VS2022 throws error that the extension for WPF template studio 5.2 misbehaves and suggests to disable the extension.

I uninstalled Template Studio completely and reset visual studio and tried but template studio never works and never goes past the error.

Suggestion: I use C# template and then convert whole thing line by line to VB and project works fine in VB environment. But to use the TS for page addition or feature addition, need to work with C# environment and this error pops up.

**Comment by mikebattista** [comment] 2022-09-06 16:55
Duplicate of #4589

**Closed by mikebattista** 2022-09-06 16:55 UTC
Labels: Needs: Triage :mag:
