### ISSUE TITLE
MAUI Templates

### ISSUE THREAD

**Issue by saigkill** [microsoft/TemplateStudio#4592] opened 2022-08-23 18:55 UTC
### Describe the solution you'd like

In general we have some project templates (Preinstalled and Enterprise). It could be useful, if we can have a template studio for MAUI. Maybe just choose that platforms, what are needed. In Preinstalled and Enterprise it creates a full project with all possible targets. 
Also a set of additional Pages could be useful. 

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mikebattista** [comment] 2022-08-25 20:56
Duplicate of #4117

**Closed by mikebattista** 2022-08-25 20:56 UTC
Labels: Needs: Triage :mag:
