### ISSUE TITLE
Unable to add page

### ISSUE THREAD

**Issue by sbeaudoin** [microsoft/TemplateStudio#4566] opened 2022-07-09 19:21 UTC
### Describe the bug

Using VS 2022 Enterprise Version 17.3.0 Preview 2.0 and the Template Studio for WinUI extension Version 5.1.  I am supposed to be able to add a page to a Template Studio generated project, but I can't find anything to do so.

### To Reproduce

1. Using VS 2022 Enterprise Version 17.3.0 Preview 2.0, create a new WinUI project with Template Studio Version 5.1.
2. Right click on the Views folder.
3. I expect to see a way to manage the project with the Template Studio wizard but there is no such option.
4. Right click on the WinUI project.
5. I expect to see a way to manage the project with the Template Studio wizard but there is no such option.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  2022 Enterprise v17.3 Preview 2
 - Template Studio Wizard Version: 5.1
 - Windows Build: Windows 10 21H2 v19044.1766

**Comment by mikebattista** [comment] 2022-07-10 17:19
Editing projects will be supported in the next update by right-clicking the Project -> Add -> New Item (Template Studio).

Duplicate of #4535.

**Closed by mikebattista** 2022-07-10 17:19 UTC
Labels: bug, Needs: Triage :mag:

**Comment by mikebattista** [comment] 2022-07-27 22:38
Version 5.2 just shipped with the edit project menu reenabled.

See https://github.com/microsoft/TemplateStudio/releases/tag/v5.2 for details.
