### ISSUE TITLE
The  foreground of App name always white

### ISSUE THREAD

**Issue by XiaoYQ-GitHub** [microsoft/TemplateStudio#4629] opened 2023-02-16 10:47 UTC
### Describe the bug

The  foreground of App name always white No matter which theme

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment] 2023-02-16 18:12
Duplicate of #4630

**Closed by mikebattista** 2023-02-16 18:12 UTC
Labels: bug, Needs: Triage :mag:
