### ISSUE TITLE
Template Studio fails with `System.MissingMethodException` while clicking on "Create"

### ISSUE THREAD

**Issue by akash07k** [microsoft/TemplateStudio#4707] opened 2023-08-15 17:23 UTC
### Describe the bug

I'm using Visual Studio 17.8 Preview 1 and latest Template Studio (5.4).
When I try to create any project by choosing Template Studio either for WPF or WinUI, it fails with System.MissingMethodException.
Below is the complete stack trace:
```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<Microsoft.TemplateEngine.Abstractions.ITemplate> Microsoft.TemplateEngine.Edge.Settings.ScanResult.get_Templates()'.
   at Microsoft.Templates.Core.TemplatesRepository.GetAll()
   at Microsoft.Templates.Core.TemplatesRepository.GetSupportedProjectTypes(UserSelectionContext context)
   at Microsoft.Templates.Core.TemplatesRepository.GetProjectTypes(UserSelectionContext context)
   at Microsoft.Templates.UI.Services.DataService.LoadProjectTypes(ObservableCollection`1 projectTypes, UserSelectionContext context)
   at Microsoft.Templates.UI.ViewModels.NewProject.ProjectTypeViewModel.<LoadDataAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.ViewModels.NewProject.MainViewModel.<OnTemplatesAvailableAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Views.NewProject.NewProjectWizardShell.<OnLoaded>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Microsoft.Internal.VisualStudio.PlatformUI.WindowHelper.ShowModal(Window window, IntPtr parent)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.<ShowModalAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.<>c__DisplayClass7_0.<<ShowModal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.Templates.UI.VisualStudio.GenShell.VsGenShellUI.ShowModal(IWindow shell)
   at Microsoft.Templates.UI.Launcher.WizardLauncher.LaunchWizardShell(IWizardShell wizardShell)
   at Microsoft.Templates.UI.Launcher.WizardLauncher.StartWizard(IWizardShell wizardShell, WizardTypeEnum wizardType)
```
I'm also attaching the logs.
[WTS_LocalEnv_20230815.log](https://github.com/microsoft/TemplateStudio/files/12346808/WTS_LocalEnv_20230815.log)

### To Reproduce

1. Open Visual Studio Preview.
2. Click on "New Project.
3. Search for "Template Studio" and choose any template such as WPF/WinUI.
4. Click "Next".
5. Click on "Create" and observe

### Additional context

![image](https://github.com/microsoft/TemplateStudio/assets/6381747/b40fe1d3-b63e-442e-a161-9e861f788d7b)

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.8 Preview 1
 - Template Studio Wizard Version: 5.4
 - Windows Build: Windows Insider 23521

**Comment by LeftTwixWand** [comment] 2023-08-30 13:55
Same issue

**Comment by jose8789** [comment] 2023-09-04 07:28
Same issue here too

**Comment by ThaDaVos** [comment] 2023-09-07 11:27
Sadly same issue - was really looking forward to test Template Studio - perhaps it's not compatible with the latest Visual Studio Preview or DotNet 8?

**Comment by MarcusKor** [comment] 2023-09-26 14:59
I think need to check the assembly "Microsoft.TemplateEngine.Edge.dll" under C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\17.0_9290dc47\Extensions\alz1ifqc.3ou path.

![image](https://github.com/microsoft/TemplateStudio/assets/107130484/3742f987-dc80-468d-92ad-b013f6b81512)

**Comment by MarcusKor** [comment] 2023-09-26 15:01
I couldn't find out the get_Templates() in ScanResult method of the assembly.
![image](https://github.com/microsoft/TemplateStudio/assets/107130484/2b2e2863-c33a-49e8-9bc8-9cce79975cc3)

**Comment by MarcusKor** [comment] 2023-09-26 15:03
Maybe the IReadOnlyList of its arguments is null. But the all related project template source files in there.

![image](https://github.com/microsoft/TemplateStudio/assets/107130484/faf955fc-0bf0-46f3-b1d2-4272a1ce069f)

**Comment by ReVanTis** [comment] 2023-10-10 09:45
Seems it's a similar issue of 
https://github.com/AvaloniaUI/AvaloniaVS/issues/381

**Comment by LeftTwixWand** [comment] 2023-10-11 15:32
I've submitted a new bug on https://developercommunity.visualstudio.com
And I'm going to attach the ticket link as soon as it gets reviewed

**Comment by mikebattista** [comment] 2023-10-11 17:21
Related issue we encountered in the past: https://github.com/microsoft/TemplateStudio/issues/4589.

**Comment by pratikone** [comment] 2023-10-11 19:08
Thank for reporting. I am aware of it and actively working to find root cause of it. https://developercommunity.visualstudio.com/t/Template-Studio-for-WinUI-C-crashes-V/10379299#T-ND10469906 where it was first reported. 
It looks like some internal VS api changed with preview which our templating nuget package depends. Updating templating nuget to newer one doesn't help either. I have fixed a few missing method exception by moving away from deprecated methods but it is now showing with newer apis too. 😔
While I continue to investigate it, I have filed this issue with templating team  : https://github.com/dotnet/templating/issues/6991

They have had a new nuget release which I haven't upgraded TS to, maybe that could help.

**Comment by Mysterious-Dev** [comment] 2023-10-22 13:57
@pratikone Did you test with VS 17.8 Preview 4 ? Because when I test your branch (https://github.com/microsoft/TemplateStudio/tree/runson2022), this run correctly ^^.

**Comment by pratikone** [comment] 2023-10-26 01:03
> @pratikone Have you tested with VS 17.8 Preview 4? Because when I test your branch ([`runson2022`](https://github.com/microsoft/TemplateStudio/tree/runson2022?rgh-link-date=2023-10-22T13%3A57%3A03Z)), it works fine ^^.

yes, it now works. The VS .net team fixed in preview 5. I guess 4 too.

**Closed by pratikone** 2023-10-26 01:03 UTC
Labels: bug
