### ISSUE TITLE
Creating a project based on WinUI requires UWP workload to be installed

### ISSUE THREAD

**Issue by harvinders** [microsoft/TemplateStudio#4380] opened 2021-08-04 11:25 UTC
**Describe the bug**
Try to create a project without installing UWP, following error is shown

![image](https://user-images.githubusercontent.com/8557046/128172553-2d35c84c-4202-4aa0-b626-c9f5a21c144a.png)

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  |  |Yes |

**System**

- **VS Version:** 16.10
- **WinTS Wizard Version:** 4.1.xx
- **WinTS Template Version:** 
- **Windows Build:** 1909

**Comment by mrlacey** [comment] 2021-08-05 11:09
This is a required workload for WinUI development:
https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment#required-workloads-and-components

Sadly, because of the fact WinTS also supports WPF (which doesn't need this workload) there's no way for the extension to only show up in the new project list when the workload is already installed. (At least not without splitting WinTS into separate extensions.)

This is not a bug in WinTS and if VS allowed you to go further at this point you'd end up with an app you couldn't compile. For this reason, seeing this warning message at this point is probably a good thing.

**Comment by mikebattista** [comment] 2022-01-19 21:34
We are evaluating how to decouple from unnecessary workloads when they aren't needed.

A proposal will be part of the roadmap we publish soon for review.

**Comment by mrlacey** [comment] 2022-01-26 22:24
As part of the support for VS2022, this workload dependency will be removed.
Note that currently, some of the Visual Studio designer functionality is also only available to WinUI projects when the UWP workload is installed.

**Comment by mrlacey** [comment] 2022-03-24 13:22
#4353 will address this on VS2022
We're not planning to fix this on V2019

**Closed by mrlacey** 2022-03-24 13:22 UTC
Labels: bug
