### ISSUE TITLE
CoreWebView2WebErrorStatus exists in both Microsoft.Web.WebView2.Core and Microsoft.WinUI

### ISSUE THREAD

**Issue by aureole82** [microsoft/TemplateStudio#4633] opened 2023-02-26 15:24 UTC
### Describe the bug

I get this error message for any usage of the `CoreWebView2WebErrorStatus` enum:
`The type 'CoreWebView2WebErrorStatus' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.864.35, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' and 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'`

It looks like `Microsoft.EntityFrameworkCore.SqlServer` has an indirect dependency on `Microsoft.Web.WebView2` where the WinUI assembly copied from and now the same type exists twice:
![image](https://user-images.githubusercontent.com/4819891/221424017-4f357827-40a9-4fe2-b057-8306b4a5762a.png)
Could you help me to fingerpoint to the correct originator? Thanks alot!

### To Reproduce

1. Create new project by "Template Studio for WinUI", in addition to defaults
   * Add WebView and
   * Select "Self-Contained", deselect "MSIX Packaging".
2. Add EntityFrameworkCore + SQL Server database provider to the `Core` project.
   `PM> Install-Package Microsoft.EntityFrameworkCore.SqlServer`
3. Rebuild solution.

### Additional context

It worked with the wizard 5.2.1 who used .NET 6.
I'm pretty sure this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5689.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version: 5.3
 - Template Studio Wizard Version: 17.5.0
 - Windows Build: 22H2 19045.2604

**Comment by mikebattista** [comment] 2023-02-28 23:30
Yes this is a duplicate of the issue you linked. It needs to be fixed at the platform level.

https://task.ms/39554408 is the corresponding internal bug tracking the issue.

**Closed by mikebattista** 2023-02-28 23:30 UTC
Labels: bug, Needs: Triage :mag:

**Comment by mikebattista** [comment] 2023-03-02 03:45
See https://github.com/microsoft/TemplateStudio/discussions/4632#discussioncomment-5174194 for a potential workaround.

**Comment by aureole82** [comment] 2023-03-12 15:26
@mikebattista 

I think 
> to install the lower version of Microsoft.EntityFrameworkCore.SqlServer that doesn't have Azure in its dependency.
is not possible within a multi project solution where other clients also dependent on the latest SQL Server access.
